title: Derrek Bertrand
author:
  name: Derrek Bertrand
  email: hello@derrekbertrand.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Personal website for Derrek Bertrand, a software engineer / EM who specializes in continuous improvement and outcome
  driven teams. I value empiricism, humanism and equity.
tagline: Personal Website and Blog
url: "https://www.derrekbertrand.com"

# Build settings

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  - positions

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
